### ISSUE TITLE
Please replace https://claim-tax-benefits.azurewebsites.net/login/code with:

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/cra-claim-tax-benefits#149]
Heading: Enter your personal security code

You can find your personal security code in the CRA letter about this new Claim Tax Benefits service.
For example: A5G98S4K1

Help with personal security code [Your code has 9-characters and you can find it on the CRA letter about the Claim Tax Benefits service. The letter has your name and address at the top. ]

Continue     Cancel

**Comment by nmakuch** [comment]
Closing this issue as PR 176 was merged in
