### ISSUE TITLE
Please replace https://claim-tax-benefits.azurewebsites.net/login/sin  with

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/cra-claim-tax-benefits#150]
https://claim-tax-benefits.azurewebsites.net/login/sin

Please replace page with:
Heading: Enter your Social insurance number (SIN)

Thanks, Gabrielle Roy!

Social insurance number
For example:847 339 283

Help with Social insurance number: You can find your SIN on your tax return or other correspondence from Service Canada. Service Canada also gave you a card or confirmation letter with your SIN.

Continue Cancel

**Comment by nmakuch** [comment]
Closing this issue as PR 179 was merged in
