### ISSUE TITLE
Please replace https://claim-tax-benefits.azurewebsites.net/login/dateOfBirth

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/cra-claim-tax-benefits#151]
https://claim-tax-benefits.azurewebsites.net/login/dateOfBirth
Please replace page with:
Heading - Enter your date of birth

Date of birth

For example: 09 09 1977

Day Month Year

Continue Cancel

**Comment by nmakuch** [comment]
Closing as PR 180 has been merged in
