### ISSUE TITLE
Please replace  https://claim-tax-benefits.azurewebsites.net/personal/name

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/cra-claim-tax-benefits#152]
https://claim-tax-benefits.azurewebsites.net/personal/name
Please replace page with:
Heading: Check your name is correct

CRA doesn't need your middle name.

Full name:
Gabrielle Roy

Is this your name?
Yes
No

Continue Cancel

**Comment by nmakuch** [comment]
Closing as PR 181 has been merged
