### ISSUE TITLE
Please replace https://claim-tax-benefits.azurewebsites.net/personal/residence

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/cra-claim-tax-benefits#153]
https://claim-tax-benefits.azurewebsites.net/personal/residence
Please replace page with: 
Heading: Enter your province or territory

On December 31, 2018, what was the province or territory of your home address?

[Drop down menu]

Continue  Cancel  

@pcraig3 please send non-Ontario to off-ramp without pre-warning

**Comment by nmakuch** [comment]
Closing as 186 has been merged in
