### ISSUE TITLE
Please replace https://claim-tax-benefits.azurewebsites.net/personal/address

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/cra-claim-tax-benefits#154]
https://claim-tax-benefits.azurewebsites.net/personal/address
Please replace page with:
Heading: Check your mailing address

Mailing address
Unit 202-303 Blake Blvd.
Ottawa, Ontario
K2 R 3Z9

Is this your correct address?

Yes
No

Continue Cancel
[@pcraig3 please remove note that pops up beside “No” answer]

**Comment by nmakuch** [comment]
Closing as 187 got merged in
