### ISSUE TITLE
Please replace https://claim-tax-benefits.azurewebsites.net/financial/income

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/cra-claim-tax-benefits#155]
https://claim-tax-benefits.azurewebsites.net/financial/income
Please replace page with:

Heading: Check your income information for the 2018 tax year

CRA has information about your 2018 income.  Please check this information. 
Later you will be able to enter more information to claim credits and deduct costs. 

[@pcraig3 Please keep current table but change totals to include decimal points]

Is all of this information correct?
Yes
No
Continue Cancel

[@pcraig3 please remove note that pops up beside “No” answer]

**Comment by nmakuch** [comment]
Closings as 188 got merged in
