### ISSUE TITLE
Please replace  https://claim-tax-benefits.azurewebsites.net/deductions/rrsp

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/cra-claim-tax-benefits#156]
https://claim-tax-benefits.azurewebsites.net/deductions/rrsp
Please replace page with:
Heading: Deduct your Registered Retirement Savings Plan (RRSP) contributions

Did you contribute to a Registered Retirement Savings Plan (RRSP) before March 1, 2019?”
Yes
No
Continue  Cancel

**Comment by nmakuch** [comment]
Closing as 190 got merged in
