### ISSUE TITLE
Please replace https://claim-tax-benefits.azurewebsites.net/deductions/rrsp/amount

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/cra-claim-tax-benefits#157]
https://claim-tax-benefits.azurewebsites.net/deductions/rrsp/amount

Please replace page with:

Heading -Enter your RRSP contributions

Total RRSP contributions before March 1, 2019

$ [@pcraig3 please use same box as before]

Continue Cancel

**Comment by nmakuch** [comment]
Closing as 191 got merged in
