### ISSUE TITLE
Please replace https://claim-tax-benefits.azurewebsites.net/personal/maritalStatus

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/cra-claim-tax-benefits#158]
https://claim-tax-benefits.azurewebsites.net/personal/maritalStatus

Please replace page with :
Heading - Check your marital status

Marital status
Single
Is this correct?
Yes
No
[@pcraig3 please remove note that pops up beside “No” answer]

**Comment by nmakuch** [comment]
Closing as 192 has been merged
