### ISSUE TITLE
Please replace https://claim-tax-benefits.azurewebsites.net/deductions/medical

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/cra-claim-tax-benefits#159]
Please replace page with

Heading - Claim medical expenses

Your taxes may be lower if your provincial health plan, work or private insurance didn’t cover all your medical costs or expenses.

Examples of medical costs are:

- Treatment by a medical doctor, nurse or dentist
- Prescription medicine
- Prescription glasses, hearing aids, wheelchairs, crutches and similar items
- Some service animal costs 
- Some travel expenses for medical treatment

You may be able to enter medical costs for yourself and your children. You may also be able to enter costs for your partner by marriage or common-law, and their children.

To include a child’s medical costs, the child must have been under 18 on December 31, 2018, and:
- Depended on you for support for example, with food, shelter, clothing
-  You or your partner must have had sole custody of the child

You may still be able to claim a child’s medical expenses, even if you or your partner didn’t have sole custody. Contact CRA to learn more. [button to link to CRA contact info]

Were your medical costs over X?
Yes
No

Continue Cancel

@pcraig3 X is a numerical value (X = Net income / 3% calculated on the back-end of the service, based on their net income on file)

**Comment by nmakuch** [comment]
Closing this issue as PR 216 has been merged
