### ISSUE TITLE
Please replace https://claim-tax-benefits.azurewebsites.net/deductions/medical/amount

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/cra-claim-tax-benefits#161]
Please replace page with
Heading - 
Enter medical costs

Enter total medical costs for:

- Yourself

- Your marriage or common law partner
- You or your partner’s children, if you are able to claim their costs [@pcraig3 Please hyperlink "if you are able" to https://claim-tax-benefits.azurewebsites.net/deductions/medical specifically the section that begins with "To include a child's medical costs. . ."]

If you have questions about medical costs, contact CRA:

- Phone: 1-800-959-8281 

- TTY: 1-800-665-0354

**Comment by nmakuch** [comment]
Closing this issue as 218 has just been merged
