### ISSUE TITLE
Please replace https://claim-tax-benefits.azurewebsites.net/deductions/political

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/cra-claim-tax-benefits#162]
https://claim-tax-benefits.azurewebsites.net/deductions/political
Please replace page with
Heading 
Deduct political contributions

Your taxes may be lower if you gave money to an election campaign or political party. You will need an official contribution receipt from the candidate or political party.

Do you have receipts for political contributions made in 2018?

Yes
No

**Comment by nmakuch** [comment]
Closing as 195 has been merged
