### ISSUE TITLE
Please replace https://claim-tax-benefits.azurewebsites.net/deductions/donations

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/cra-claim-tax-benefits#164]
https://claim-tax-benefits.azurewebsites.net/deductions/donations
 
Please replace page with

Heading - Deduct charitable donations

Your taxes may be lower if you gave money to a charity or similar organization. You will need an official tax receipt. The charity or organization must be registered with the government to give the receipt. You can enter any donations from the last five that you didn't already deduct from your taxes.

Do you have tax receipts for charitable donations?
Yes
No

Continue Cancel

**Comment by nmakuch** [comment]
closing as 197 has been merged
