### ISSUE TITLE
** Note : this is for two different pages, page:/  https://claim-tax-benefits.azurewebsites.net/trillium/rent and page:/ https://claim-tax-benefits.azurewebsites.net/trillium/rent/**amount

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/cra-claim-tax-benefits#166]
** Note : this is for two different pages, page:/ https://claim-tax-benefits.azurewebsites.net/trillium/rent and page:/ https://claim-tax-benefits.azurewebsites.net/trillium/rent/**amount

Please  replace with several new pages:

New Page 
Heading:  The Ontario Trillium Benefit
The Ontario Trillium Benefit (OTB) is a government payment that helps with energy, sales and property taxes. You can learn about the OTB at https://www.canada.ca/en/revenue-agency/services/child-family-benefits/provincial-territorial-programs/ontario-trillium-benefit-questions-answers.html

Apply for OTB on the pages that follow.

Continue Cancel

New Page

Heading: Apply for OTB:rent payments

Did you pay rent for the place you lived most of 2018?

Yes 
No 

Continue Cancel

New Page
Heading: 
Enter your rent payments to apply for OTB

The government might ask for your rent receipts.

How much total rent did you pay for the place you lived most of 2018?

Continue Cancel

**Comment by nmakuch** [comment]
closing as 199 has been merged
