### ISSUE TITLE
** Note this is for two different pages, page:/ https://claim-tax-benefits.azurewebsites.net/trillium/propertyTax and page/ https://claim-tax-benefits.azurewebsites.net/trillium/propertyTax/amount  **

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/cra-claim-tax-benefits#167]
** Note this is for two different pages, page:/ https://claim-tax-benefits.azurewebsites.net/trillium/propertyTax and page/ https://claim-tax-benefits.azurewebsites.net/trillium/propertyTax/amount  **
 
Please replace page with:
Heading:  - Apply for OTB: property tax

Did you pay property tax for the place you lived most of  2018?
Continue Cancel

Next page
Heading - Enter your property tax payments to apply for OTB

The government might ask for your property tax receipts.

How much total property tax did you pay for the place you lived most of 2018?

Continue Cancel

**Comment by nmakuch** [comment]
Closing as 200 has been merged
