### ISSUE TITLE
Please replace https://claim-tax-benefits.azurewebsites.net/trillium/studentResidence

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/cra-claim-tax-benefits#168]
https://claim-tax-benefits.azurewebsites.net/trillium/studentResidence

Please replace page with:
Heading: : Apply for OTB - student residence 

Did you live in a university, college or private school student residence in 2018?  

Yes No

Continue Cancel

Learn more about student residences: https://www.ontario.ca/data/designated-postsecondary-residences

**Comment by nmakuch** [comment]
Closing as 219 has just been merged
