### ISSUE TITLE
Please replace https://claim-tax-benefits.azurewebsites.net/trillium/energy/amount

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/cra-claim-tax-benefits#171]
Please replace page with:
Heading: 
Enter your home energy costs to apply for OTB

The government might ask for receipts later. The receipts must cover energy costs for a home on  reserve where you lived most of 2018.

What were your total home energy costs on reserve?

Continue Cancel

**Comment by nmakuch** [comment]
Closing this issue as 221 has been merged
