### ISSUE TITLE
Please replace https://claim-tax-benefits.azurewebsites.net/trillium/longTermCare/amount

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/cra-claim-tax-benefits#172]
Please replace page with:
Heading:  Apply for OTB: long-term care home costs

You may live in a long-term care home or facility if costs such as nursing or personal support are combined with your rent.  The home must be public or non-profit. This means that a charity, city, First Nations, or similar organization manages the home. 

Did you live in a long-term care home in 2018?

Yes 
No

Continue Cancel

**Comment by nmakuch** [comment]
closing this issue as 222 has been merged in
