### ISSUE TITLE
Please replace https://claim-tax-benefits.azurewebsites.net/trillium/longTermCare/amount

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/cra-claim-tax-benefits#173]
https://claim-tax-benefits.azurewebsites.net/trillium/longTermCare/amount
Please replace page with:
Heading: 
Enter your long-term care home costs to apply for OTB

The government might ask for your long-term care receipts.

How much were your total long-term care costs in 2018?

Continue Cancel

**Comment by nmakuch** [comment]
Closing as 224 has just been merged
