### ISSUE TITLE
Please replace page with https://claim-tax-benefits.azurewebsites.net/deductions/climate-action-incentive

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/cra-claim-tax-benefits#174]
https://claim-tax-benefits.azurewebsites.net/deductions/climate-action-incentive
Please replace page with:
Heading:  The Climate Action Incentive
The Climate Action Incentive (CAI) lowers the amount of tax you pay. It could also increase the money you get back from filing taxes.

Your CAI is greater if you live in a small and rural community.[@pcraig3 Please move the blue question and drop down up here, and give the cities in as a list rather than in paragraph form:  How do I know if I live in a small and rural community?
You live in a small and rural community if you don’t  live in:

Barrie
Belleville
Brantford
Greater Toronto Area 
Guelph
Hamilton
Kingston
Kitchener-Cambridge-Waterloo
London
Oshawa
Ottawa 
Peterborough
St. Catharines-Niagara
Sudbury
Thunder Bay
Windsor] 

Did you live in a small and rural community in 2018?
Yes
No
Continue Cancel

**Comment by nmakuch** [comment]
Closing as 225 has been merged
