### ISSUE TITLE
Please make the following changes to https://claim-tax-benefits.azurewebsites.net/review

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/cra-claim-tax-benefits#175]
https://claim-tax-benefits.azurewebsites.net/review
Please replace first two paragraphs with:

Based on your information, below are tax benefits, and money you will get back from your 2018 taxes. Please check this information. If something looks wrong, contact CRA before you file at:

- Phone: 1-800-959-8281 

- TTY: 1-800-665-0354

Please replace “Your annual benefits” with “Your 2018 tax benefits”
Please replace “Your projected refund” with “Your expected refund”

Please replace "I confirm that" with "As far as I know, everything in this tax return is correct:"

Please replace "Submit" with "File my taxes now"

**Comment by nmakuch** [comment]
closing as 227 has been merged in
