### ISSUE TITLE
Please replace https://claim-tax-benefits.azurewebsites.net/confirmation

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/cra-claim-tax-benefits#177]
https://claim-tax-benefits.azurewebsites.net/confirmation

Please replace page with:
Heading:   You have filed your 2018 taxes

Your 2018 filing number is 5H3P9IO5816

Give CRA this number if you need help or information. You can contact CRA by:

Phone: 1-800-959-8281 
TTY: 1-800-665-0354

You can also get help at a free tax clinic. Visit canada.ca/taxes-help to find your nearest clinic.

Print summary of your 2018 tax return (blue button)

It is important to read your Notice of Assessment which shows:

- That you filed taxes
- If you will get benefits or money back
- If you owe money to CRA

Download your 2018 notice of assessment (blue button)

**Comment by nmakuch** [comment]
Closing this issue as PR 228 has been merged
