### ISSUE TITLE
HOLD https://claim-tax-benefits.azurewebsites.net/deductions/medical

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/cra-claim-tax-benefits#252]
Please break into several pages:
(Page 1)  Heading -Medical costs

Pls delete: "Your taxes may be lower if your provincial health plan, work or private insurance didn’t cover all your medical costs or expenses."

Under  "Examples of medical costs are:"  please make the drop down part of the main page, instead of hidden.

Then please put:
Were all of you and your family's medical expenses covered by a provincial health plan, work or private insurance?

Yes/No
Continue Cancel
[If yes, go to political contribution page
If no go to next med expenses page]

Next page https://claim-tax-benefits.azurewebsites.net/deductions/medical/amount) 
Heading: Medical costs for you and your family 

Medical costs may include costs for your marriage or common law partner, your children and your partner's children.

To include a child's medical costs:
-  The child must have been younger than 18 on December 31, 2018
- The child must have depended on your support for example, with food, shelter, clothing
- You or your partner must have had sole custody of the child

Do you have medical costs for someone other than yourself, your children, your partner or their children? 

Yes/No
Yes - additional dependents detour
No - next page

Continue Cancel

Next page Heading: Amount of medical costs

Were you or your family's medical costs over x?
Yes/No
Continue /cancel
No goes to political contribution page
Yes goes to page to Enter medical costs

Next page- Heading -Enter medical costs
Total medical costs
[Box for entering as on other pages]
Continue/Cancel

DETOUR: additional dependent (not child / spouse) →

Title: File without your other dependents

Body: You can still use this online service, but you won't be able to include other dependents.

If you want to include other dependents, you may be able to get help at a tax clinic. Visit https://www.canada.ca/en/revenue-agency/services/tax/individuals/community-volunteer-income-tax-program/need-a-hand-complete-your-tax-return.html#eligible to learn if you can use a tax clinic.  You can add dependents at a tax clinic.

Learn more about dependents [please create hyperlink]: https://www.canada.ca/en/revenue-agency/services/tax/individuals/topics/about-your-tax-return/tax-return/completing-a-tax-return/deductions-credits-expenses/line-305-amount-eligible-dependant/you-claim-amount-eligible-dependant-line-305-6.html#targetText=You%20have%20told%20the%20CRA%3A&targetText=The%20dependant%20you%20supported%20was,in%20physical%20or%20mental%20functions

For more information, contact CRA by:

Phone: 1-800-959-8281 	
TTY (text telephone): 1-800-665-0354

Continue

**Comment by pcraig3** [comment]
Closing this as we have removed the medical deductions questions.
