### ISSUE TITLE
Incorrect name (after log-in) → Detour

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/cra-claim-tax-benefits#261]
https://claim-tax-benefits.azurewebsites.net/offramp/name
Title: Change your name with CRA

Body:
You can still use this online service with the name on your CRA file.

CRA has instructions for changing the name on your file. (hyperlink under "instructions" to https://www.canada.ca/en/revenue-agency/services/tax/individuals/frequently-asked-questions-individuals/should-you-tell-cra-about-your-change-name.html)

For more information, contact CRA by:

- Phone: 1-800-959-8281 	

- TTY(text telephone): 1-800-665-0354

Continue button  [takes you back into service ]

**Comment by nmakuch** [comment]
@YedidaZalik, could we change the full url to a hyperlink? Just takes up a lot of space on screen when it's fully typed out :s

**Comment by YedidaZalik** [comment]
@nmakuch  many of the urls are long, and I'm happy for your to switch to a hyperlink on this and other pages  - wherever you think it makes sense to do so! 
Sorry it took so long to reply.

**Comment by nmakuch** [comment]
Closing this issue as 273 has been merged
