### ISSUE TITLE
Changes to https://claim-tax-benefits.azurewebsites.net/confirmation

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/cra-claim-tax-benefits#340]
Please add blue banner similar to Lite version for filing code

**Please replace:**
You will get a notice of reassessment if CRA makes any changes.

If CRA owes you money, then:

CRA will put the money in your bank account if you arranged direct deposit.
your cheque comes in the mail if you didn’t arrange direct deposit.
Thank you for using our service. Please share your feedback.

**With:**
If CRA owes you money, then:
									
• CRA will put it in your bank account if you registered for direct deposit 
• your cheque comes with the notice if you did not register for direct deposit.
									
Thank you for using the Claim Tax Benefits service. Please share your feedback to improve this service.  [hyperlink under "share your feedback"]
								
____________________
**[French] Please replace:**
Vous recevrez un avis de nouvelle cotisation si l’ARC apporte des modifications.

Si l’ARC vous doit de l’argent, alors : 

• l’ARC déposera l’argent dans votre compte bancaire si vous êtes inscrit au dépôt direct.
• vous recevrez un chèque par la poste si vous n’êtes pas inscrit au dépôt direct.

Merci d’avoir utilisé notre service. Faites-nous part de vos commentaires.

**With:**
Si l’ARC vous doit de l’argent, alors : 

• l’ARC déposera l’argent dans votre compte bancaire si vous êtes inscrit au dépôt direct.
• vous recevrez un chèque en même temps que votre avis si vous n’êtes pas inscrit au dépôt direct.

Merci d’avoir utilisé le service _Réclamer des avantages fiscaux_. N’hésitez pas à envoyer vos commentaires pour aider à l’améliorer. [hyperlink under "envoyer vos commentaires"]

**Comment by brdunfield** [comment]
Closed by #343 #344 , and #346
