### ISSUE TITLE
Changes to https://claim-tax-benefits.azurewebsites.net/vote/confirmRegistration

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/cra-claim-tax-benefits#364]
As explained by @brianhendrick1 please give more visual space to the explanation beside the last box "You allow CRA to give your name, address, date of birth and citizenship status to Elections Canada. Elections Canada uses the information to update voter records.

Thanks!

**Comment by pcraig3** [comment]
Closing this issue in favour of #468
