### ISSUE TITLE
Changes to screening question and off-ramp Step 1 of 7

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/cra-claim-tax-benefits#436]
Please change question for https://claim-tax-benefits.azurewebsites.net/eligibility/taxable-income

For under 65 to
"Was your 2019 income less than $12,070?"
For over 65 to:
"Was your 2019 income less than $19, 564?"

Please change offramp for https://claim-tax-benefits.azurewebsites.net/offramp/taxable-income
For under 65, first line should change to
"You cannot use this online service because your 2019 income was $12,070 or higher."
For over 65, first line should change to
"You cannot use this online service because your 2019 income was $19,564 or higher."

Thanks!

**Comment by pcraig3** [comment]
This issue was closed by #437
