### ISSUE TITLE
French translation of screening questions and accompanying offramps

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/cra-claim-tax-benefits#439]
Please add the French translation which can be found in this document https://docs.google.com/document/d/1L0twEnaQu3WilNhUKftV6OmEQl7MPtET-kZ1o2QNrA0/edit

Merci beaucoup!

**Comment by nmakuch** [comment]
Forgot to reference it in my PR but, [#447](https://github.com/cds-snc/cra-claim-tax-benefits/pull/447) resolved this
