### ISSUE TITLE
French translation of confirmation page with benefit table

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/cra-claim-tax-benefits#441]
Please add the following French translation:
https://docs.google.com/document/d/1pAf9hU6yDh2IoU9ffxyn-DCHx3WvMoZoTHt3W18C2kc/edit#

Merci beaucoup!

**Comment by nmakuch** [comment]
Forgot to reference it in my PR but, [#447](https://github.com/cds-snc/cra-claim-tax-benefits/pull/447) resolved this
