### ISSUE TITLE
Translations for /deductions/senior-public-transit and /deductions/senior-public-transit/amount

### ISSUE THREAD

**Issue by nmakuch** [cds-snc/cra-claim-tax-benefits#453]
## 1) Senior Public Transit page for translation
<img width="1392" alt="Screen Shot 2020-01-28 at 10 18 11" src="https://user-images.githubusercontent.com/30609058/73276872-5d65e180-41b7-11ea-8ddc-c2c274fd301c.png">

## 2) Senior Public Transit AMOUNT page for translation
<img width="1392" alt="Screen Shot 2020-01-28 at 10 18 21" src="https://user-images.githubusercontent.com/30609058/73276871-5d65e180-41b7-11ea-8e19-9bba8341231c.png">

**Comment by EliseKa** [comment]
1) Senior Public Transit page for translation

**Transport en commun pour personnes âgées**
Avez-vous utilisé le transport en commun en 2019?
Oui
Non

2) Senior Public Transit AMOUNT page for translation

**Inscrivez vos frais de transport en commun pour 2019**
Le gouvernement pourrait vous demander vos reçus de frais de transport.
Montant total des frais payés pour le transport en commun
