### ISSUE TITLE
Typography nerd stuff 🤓

### ISSUE THREAD

**Issue by pcraig3** [cds-snc/cra-claim-tax-benefits#468]
# Typography nerd stuff 🤓

Okay, let's talk about typography for a bit.

Very early on we started building this site with a “we need a demo in 3 weeks” timeline.

As a starting basis, I grabbed the Canada.ca theme from CRA and we build out the first bunch of pages that way. Here is an example Canada.ca page vs our first-ever home page.

| CRA website ([E-services](https://www.canada.ca/en/revenue-agency/services/e-services/e-services-businesses.html)) | CTB homepage  |
|--------|-------|
| <img width="1469" alt="Screen Shot 2020-02-05 at 6 22 45 PM" src="https://user-images.githubusercontent.com/2454380/73892307-97cd1f80-4844-11ea-99fe-36aa4265f899.png">  | <img width="1469" alt="Screen Shot 2020-02-05 at 6 21 52 PM" src="https://user-images.githubusercontent.com/2454380/73892260-6c4a3500-4844-11ea-9b5d-3bc404b0b3a9.png">     |

After the initial setup, there were basically 2 rounds of pull request specifically about on our site-wide typography.

1. [Fixed some layout bugs to normalize margins and bottom spacing](https://github.com/cds-snc/cra-claim-tax-benefits/pull/13) (click for pics)
2. [Adjusted line height and shrunk text sizes on mobile](https://github.com/cds-snc/cra-claim-tax-benefits/pull/102) (also click for pics)

Obviously we've done a lot of one-off CSS adjustments and we've added new components from time to time as well, but those two pull requests above are the main "site-wide typography rationalizations" we've done so far.

## No clear guidelines in the Canada.ca theme

The Canada.ca theme doesn’t really have an opinion on font measure (ie, 'measure' == line length). On a large screen, a 2/3rds column is roughly the right line length, but if we use CRA as an example, there's full-width lines all over the place. 

| [NETFILE - Overview](https://www.canada.ca/en/revenue-agency/services/e-services/e-services-individuals/netfile-overview.html) | [E-services](https://www.canada.ca/en/revenue-agency/services/e-services.html) | [E-services for businesses](https://www.canada.ca/en/revenue-agency/services/e-services/e-services-businesses.html) |
|-------|--------|-------|
|  ✅2/3rds: ~70-80 character lines   |  ❌ full-width: > 110 character lines    |   ❌ full-width: > 110 character lines    |
| <img width="1469" alt="Screen Shot 2020-02-05 at 6 41 34 PM" src="https://user-images.githubusercontent.com/2454380/73893325-4ffbc780-4847-11ea-8d3d-7da8a74add9e.png">    | <img width="1469" alt="Screen Shot 2020-02-05 at 6 41 55 PM" src="https://user-images.githubusercontent.com/2454380/73893315-4d00d700-4847-11ea-87dc-05fc9dd4b08e.png">    | <img width="1469" alt="Screen Shot 2020-02-05 at 6 40 52 PM" src="https://user-images.githubusercontent.com/2454380/73893328-512cf480-4847-11ea-81b6-aaafa8a5d1ee.png">   |

So effectively we’ve inherited this lack of hard and fast rules — which means that we're not bound to anything in particular, but also that we have the responsibility to come up with the rules ourselves.

## Our “rules” for line length

We have 3 typography rules right now:
1. Forms are a 1/3 width on desktop (eg, [rent page (question, buttons, details element)](https://claim-tax-benefits.azurewebsites.net/trillium/rent))
2. Some content pages are 4/5 width (eg, [start page](https://claim-tax-benefits.azurewebsites.net/start), [confirmation page](https://claim-tax-benefits.azurewebsites.net/confirmation)) 
3. Everything else is full-width (eg, [rent page (title, lead-in paragraph)](https://claim-tax-benefits.azurewebsites.net/trillium/rent))

Rule number 1 — the forms — are the most noticeably awkwardly-designed part of our application, so where did this come from?

## Why our forms are 1/3 width 

Expedience. At many other widths — 100%, 66%, and 50% — our inputs were really big and also our buttons were super wide.

GOV.UK Guidance recommends appropriately sizing input elements based on the intended values: https://design-system.service.gov.uk/components/text-input/#use-appropriately-sized-text-inputs

So I set 33% form widths on desktop and that was that.

Early on, when we just needed to churn out pages, our minimal ruleset was really good: super simple and no weird edge-cases to account for. Since we have so many "amount" inputs, we don't want them to span the page — we want them to be pretty small.  By constraining the size of the whole form, we got our small inputs and we could allow for different numbers of buttons. 

## Q’est ce-qu’on fait?

So that's how we started, but now we're all grown up and we are seeing some pretty awkward layouts.  In practice, we don't have that many different page templates and we pretty much always have two buttons at the bottom, so we can be more definitive about this stuff.

Ideally, we should shoot for 
- **60-80 characters** for body text
- **45-55 characters** for h1 text

The conventional recommendation is 45-75 characters per line, although [this article](https://www.viget.com/articles/the-line-length-misconception/) maintains that lines can be longer without sacrificing readability. [Practical typography](https://practicaltypography.com/line-length.html) recommends 45-90 characters per line, which seems like an acknowledgement of this.

## Specific problems to fix

So those are the general principles we should aim for, but we don't have "general" problems, we have specific ones. There are 3 main problems we see while going through the application.

### 1. Question text and hint text is way too short.

We're maxing out around 35-50 characters: we could comfortably double this.

| question lines are too short | hint text lines are too short |
|--------|-------|
|  [Property tax](https://claim-tax-benefits.azurewebsites.net/trillium/propertyTax)      | [Long-term care](https://claim-tax-benefits.azurewebsites.net/trillium/longTermCare)    |
| <img width="522" alt="Screen Shot 2020-02-05 at 5 52 28 PM" src="https://user-images.githubusercontent.com/2454380/73894937-fa75e980-484b-11ea-93bb-60b2bc6b8843.png">   | <img width="517" alt="Screen Shot 2020-02-05 at 5 52 04 PM" src="https://user-images.githubusercontent.com/2454380/73894939-fba71680-484b-11ea-8b35-2f56f7d7adf2.png">    |

### 2. Full width paragraphs are too long

We're way over 100 characters. On the start page and the confirmation pages, we're at 80% width, which is more in line with what we want.

| full width paragraphs are too long | (again) |
|--------|-------|
|  [Rent page](https://claim-tax-benefits.azurewebsites.net/trillium/rent)      | [Rent page](https://claim-tax-benefits.azurewebsites.net/trillium/rent)    |
| <img width="1183" alt="Screen Shot 2020-02-05 at 5 51 01 PM" src="https://user-images.githubusercontent.com/2454380/73894942-fc3fad00-484b-11ea-99c7-e8549f93d906.png">   | <img width="1203" alt="Screen Shot 2020-02-05 at 5 50 51 PM" src="https://user-images.githubusercontent.com/2454380/73894944-fcd84380-484b-11ea-845f-4c8fed85f7cd.png">  |

3. Titles are too long, even though they are 60 chars.

Even though we're within the 45-90 character limit, our titles look far too long on a full-width page size. We should try cap these at something more more sensible. **However**, we still want the red line to be full-width, as this matches the Canada.ca theme.

| full-width titles are too long | 
|--------|
|  [Room and board costs in long term care](https://claim-tax-benefits.azurewebsites.net/trillium/longTermCare/type/roomAndBoard)    |
| <img width="1197" alt="Screen Shot 2020-02-05 at 5 52 54 PM" src="https://user-images.githubusercontent.com/2454380/73894932-f944bc80-484b-11ea-92b4-2ce40ecedf1f.png">  |

**As a final point, the font size on the CRA's Canada.ca theme is a smidge smaller than ours, so we should match it.**

**Comment by brdunfield** [comment]
Are we suggesting to make titles multi-line? Or are we suggesting content changes that bring our titles down to a more sensible character length?

**Comment by pcraig3** [comment]
We're only changing CSS for this story so let’s do something like this:

<img width="1500" alt="Screen Shot 2020-02-06 at 1 56 33 PM" src="https://user-images.githubusercontent.com/2454380/73968971-8a697100-48e8-11ea-9041-89383595c0cf.png">

Having said that, this is the lowest priority thing on the list so let's leave it till the end.

**Comment by pcraig3** [comment]
😗 👌
