### ISSUE TITLE
FR changes to cancel page

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/cra-claim-tax-benefits#552]
Please create French cancel page with the content below. Merci!

[Heading] Annuler la session

Voulez-vous vraiment annuler votre session?

Si vous annulez la session, aucune de vos réponses ne sera enregistrée. 
Vous devrez commencer une nouvelle session si vous souhaitez produire votre déclaration de revenus avec le présent service.

Annuler la session           Page précédente

**Comment by pcraig3** [comment]
These changes went in last week as part of https://github.com/cds-snc/cra-claim-tax-benefits/pull/551
