### ISSUE TITLE
postCode feels confusing

### ISSUE THREAD

**Issue by sboisvert** [cds-snc/cra-claim-tax-benefits#8]
In https://github.com/cds-snc/cra-claim-tax-benefits/blob/34435cf4b0655ffd30b3d310f4c569193f3142b6/routes/login/login.controller.js#L13
the function is called postCode, which I assume is meant to reference POSTing the access code but it feels like it's like the postal code or something. 

Given that I assume we'll have many similar functions handling the posting of data, should we rename them to something more clear?

cc @pcraig3 @katedee

**Comment by pcraig3** [comment]
we could call it `postLoginCode`?

**Comment by pcraig3** [comment]
resolved since #9
