### ISSUE TITLE
Personal access code or personal code consistency

### ISSUE THREAD

**Issue by rossferg** [cds-snc/cra-claim-tax-benefits#93]
https://claim-tax-benefits.azurewebsites.net/login/code refers to a 'personal access code'.

https://claim-tax-benefits.azurewebsites.net/login/sin refers to a 'personal code'.

Consider changing 'Now that we have your personal code, we need' to 'Now that we have your personal access code, we need' for consistency and to make it clearer to the user which code is being referred to.

**Comment by YedidaZalik** [comment]
@pcraig3 I'm recommending revisions to this page so the whole thing may change - I've noted the consistency issue in the content audit

**Comment by pcraig3** [comment]
Thanks for having a look, @YedidaZalik!
