### ISSUE TITLE
Purpose of 'Confirm your most recent benefit payment' step is confusing

### ISSUE THREAD

**Issue by rossferg** [cds-snc/cra-claim-tax-benefits#94]
It is not clear from the title of 'Confirm your most recent benefit payment' what the purpose of this step is in relation to the 'Change your mailing address' request.

Don't rely on users reading the explanatory text below. Clarify purpose of https://claim-tax-benefits.azurewebsites.net/login/auth?redirect=%2Fpersonal%2Faddress%2Fedit step using the H1. For example, 'Confirm your most recent benefit payment to change address' or 'for verification'.

**Comment by YedidaZalik** [comment]
@pcraig3 I think I need to rewrite this page (included in content audit)

**Comment by pcraig3** [comment]
@YedidaZalik, yep sounds good to me. Will keep the issue open the rewrite happens 👍

**Comment by pcraig3** [comment]
This page is gone since #138 went in and nuked half the app.
