### ISSUE TITLE
Total amounts in Confirm income table do not match

### ISSUE THREAD

**Issue by rossferg** [cds-snc/cra-claim-tax-benefits#96]
On https://claim-tax-benefits.azurewebsites.net/financial/income, the Total amount in breakdown table heading ($21,305) does not match Total amount in summary row below ($21,305.10).

**Comment by YedidaZalik** [comment]
@pcraig3 is this an error in the calculator or was there a design decision to round the totals down, and if so, what was the reason for that ?

**Comment by pcraig3** [comment]
@YedidaZalik, Sorry, this isn't really a content story, my mistake. 

There currently is no calculator — it's (almost) all just static text.

**Comment by YedidaZalik** [comment]
resolved
