### ISSUE TITLE
Spell out RRSP acronym

### ISSUE THREAD

**Issue by rossferg** [cds-snc/cra-claim-tax-benefits#97]
IDKYA 

Spell out RRSP acronym on https://claim-tax-benefits.azurewebsites.net/start and https://claim-tax-benefits.azurewebsites.net/deductions/rrsp.

For consistency with style elsewhere (eg. SIN on /start) and to make it clearer to the user what is being asked for.

**Comment by YedidaZalik** [comment]
@pcraig3 agree that it needs to be spelled out but recommending other changes to this page so may be best to do all changes at once

**Comment by pcraig3** [comment]
Yup, sounds good.

**Comment by YedidaZalik** [comment]
resolved
