### ISSUE TITLE
Reconsider use of 'your self' on /deductions/medical

### ISSUE THREAD

**Issue by rossferg** [cds-snc/cra-claim-tax-benefits#98]
Change 'You can claim medical expenses for your self, spouse or common-law partner, and' to 'You can claim medical expenses for yourself, your spouse or common-law partner, and' on /deductions/medical

**Comment by YedidaZalik** [comment]
@pcraig3 I agree that it should be "yourself" but I am recommending further changes to this page, so you may prefer to make all the changes at once (I have included the "yourself" change in the content audit)

**Comment by pcraig3** [comment]
Sounds good! Will close the issue once we make the further changes.

**Comment by YedidaZalik** [comment]
resolved
